name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build -t my-github-action-appp .

    - name: Push Docker image to Docker Hub
      uses: docker/build-push-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: docker.io
        image: my-github-action-appp:latest 
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag viswanatha/my-github-action-appp:${{ github.sha }}
      
    - name: Docker Push
      run: docker push viswanatha/my-github-action-app:${{ github.sha }}
