name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build . -t viswanatha/my-github-action-app:${{ github.sha }} -f Dockerfile

    - name: Docker Login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.io -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Docker Push
      run: docker push viswanatha/my-github-action-app:${{ github.sha }}
